version: "3"
services:
  app:
    # image: node:16
    build:
      context: .
    # volumes:
    #   - .:/home/
    # command:
    #   - bash
    #   - -c
    #   -  sleep infinity
    network_mode: host